close all;
clear all;

datapath1='a1.dat';
load(datapath1,'a1');
datapath2='a2.dat';
load(datapath2,'a2');
datapath3='a3.dat';
load(datapath3,'a3');
datapath4='a4.dat';
load(datapath4,'a4');
datapath5='a5.dat';
load(datapath5,'a5');
datapath6='a6.dat';
load(datapath6,'a6');

datapath1='b1.dat';
load(datapath1,'b1');
datapath2='b2.dat';
load(datapath2,'b2');
datapath3='b3.dat';
load(datapath3,'b3');
datapath4='b4.dat';
load(datapath4,'b4');
datapath5='b5.dat';
load(datapath5,'b5');
datapath6='b6.dat';
load(datapath6,'b6');

datapath1='c1.dat';
load(datapath1,'c1');
datapath2='c2.dat';
load(datapath2,'c2');
datapath3='c3.dat';
load(datapath3,'c3');
datapath4='c4.dat';
load(datapath4,'c4');
datapath5='c5.dat';
load(datapath5,'c5');
datapath6='c6.dat';
load(datapath6,'c6');

datapath1='d1.dat';
load(datapath1,'d1');
datapath2='d2.dat';
load(datapath2,'d2');
datapath3='d3.dat';
load(datapath3,'d3');
datapath4='d4.dat';
load(datapath4,'d4');
datapath5='d5.dat';
load(datapath5,'d5');
datapath6='d6.dat';
load(datapath6,'d6');
